export const metadata = {
    title: '18 U.S.C. § 2257 Compliance - VideoGen',
};

export default function Model2257Page() {
    return (
        <div style={{ maxWidth: '800px', margin: '0 auto', padding: '60px 20px', lineHeight: '1.8', color: 'var(--text-secondary)' }}>
            <h1 style={{ color: 'var(--text-primary)', marginBottom: '24px' }}>18 U.S.C. § 2257 Compliance Exemption</h1>
            <p style={{ marginBottom: '16px' }}>Last updated: {new Date().toLocaleDateString()}</p>

            <div style={{ padding: '24px', background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: '8px', marginTop: '32px' }}>
                <p style={{ marginBottom: '16px' }}>
                    All visual depictions of individuals engaging in sexually explicit conduct appearing on or generated by this website are computer-generated imagery (CGI) created by artificial intelligence.
                </p>
                <p style={{ marginBottom: '16px' }}>
                    <strong>No real persons are depicted in the AI-generated content on this platform.</strong>
                </p>
                <p>
                    As such, the content falls outside the scope of 18 U.S.C. § 2257 and 28 C.F.R. § 75, which mandate record-keeping for depictions of actual human beings. The platform strictly prohibits the generation of deepfakes or non-consensual imagery of real, identifiable individuals.
                </p>
            </div>
        </div>
    );
}
