export const metadata = {
    title: 'Terms of Service - VideoGen',
};

export default function TermsPage() {
    return (
        <div style={{ maxWidth: '800px', margin: '0 auto', padding: '60px 20px', lineHeight: '1.8', color: 'var(--text-secondary)' }}>
            <h1 style={{ color: 'var(--text-primary)', marginBottom: '24px' }}>Terms of Service</h1>
            <p style={{ marginBottom: '16px' }}>Last updated: {new Date().toLocaleDateString()}</p>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ color: 'var(--text-primary)', marginTop: '24px', marginBottom: '16px' }}>1. Age Restriction</h2>
                <p>This service contains adult content. You must be at least 18 years of age or the age of majority in your jurisdiction to use this service. By accessing this platform, you represent and warrant that you meet this age requirement. Any false declaration of age is solely the responsibility of the user.</p>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ color: 'var(--text-primary)', marginTop: '24px', marginBottom: '16px' }}>2. Prohibited Content</h2>
                <p>You may not generate, distribute, or promote content that violates any laws. Specifically, you agree NOT to generate:</p>
                <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
                    <li style={{ marginBottom: '8px' }}>Any content depicting or resembling minors in any sexual or suggestive context.</li>
                    <li style={{ marginBottom: '8px' }}>Deepfakes or non-consensual imagery resembling real, identifiable individuals without explicit written consent.</li>
                    <li style={{ marginBottom: '8px' }}>Content that promotes illegal activities, violence, or CSAM (Child Sexual Abuse Material).</li>
                </ul>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ color: 'var(--text-primary)', marginTop: '24px', marginBottom: '16px' }}>3. Account Suspension and BAN Policy</h2>
                <p>We actively monitor prompts and generated content. Any violation of the Prohibited Content rules (especially attempts to generate minors) will result in immediate account suspension, permanent BAN, and IP blocking without refund. We co-operate with law enforcement if necessary.</p>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ color: 'var(--text-primary)', marginTop: '24px', marginBottom: '16px' }}>4. Disclaimer of Liability</h2>
                <p>The service is provided "as is". The operators are not responsible for the content generated by users. Users hold all responsibility and liability for the content they generate, download, or share.</p>
            </section>

        </div>
    );
}
